image: Visual Studio 2015

init:
  - git config --global core.autocrlf input

clone_folder: C:\projects\ms0515btl
shallow_clone: true

matrix:
  fast_finish: false

platform:
  - Win32

configuration:
  - Debug
  - Release
  - Product

environment:
  matrix:
    - toolchain: msvc13

build:
  project: emulator\MS0515BTL-VS2013.sln

